### PR TITLE
Show recording overlay in macOS fullscreen apps, and when switching between spaces

### LINKED ISSUE #277: [BUG] Overlay is not shown over fullscreen apps on macOS
## Bug Description
Overlay is not shown over fullscreen apps on macOS. On regular desktop Spaces the overlay is visible.

### Steps to Reproduce
1. Open any app in **fullscreen**.
2. Activate **Handy**.

### Expected Behavior
- Overlay is shown **above** the currently active fullscreen app.

### Actual Behavior
- Overlay is **not** shown over fullscreen apps.
- Overlay **is** shown on normal desktop Spaces.

## System Information
**App Version:**
0.5.4

**Operating System:**
macOS 15.6.1 (24G90)

**CPU:**
Apple M1

**GPU:**
Apple M1 GPU

### LINKED ISSUE #278: [BUG] Overlay does not follow Space changes
## Bug Description
When the overlay is active and the user switches to another Space (another desktop or another fullscreen app), the overlay stays on the original Space instead of following the active one.
By the way overflow is not showing over fullscreen apps #277

### Steps to Reproduce
1. Activate **Handy** overlay on **Desktop 1**.
2. Switch to **Desktop 2** or to another **fullscreen** app/Space.
3. Observe overlay visibility.

### Expected Behavior
- Overlay follows the user when switching Spaces.
- Overlay is always visible on the **current** Space.

### Actual Behavior
- Overlay remains on the Space where it was first opened.
- Overlay is **not** visible on the new Space.

## System Information
**App Version:**
0.5.4

**Operating System:**
macOS 15.6.1 (24G90)

**CPU:**
Apple M1

**GPU:**
Apple M1 GPU

### PR DESCRIPTION
**Pull request by dannysmith**
## Problem

Handy shows no visual feedback when recording in fullscreen apps on macOS, as the current Recording Overlay is not shown (#277). Similarly, the overlay is not shown when the user switches spaces (#278).

On macOS Big Sur+, standard `NSWindow` with `.always_on_top(true)` uses `NSFloatingWindowLevel` (level 3). Fullscreen apps run at `NSMainMenuWindowLevel + 1` (level 25+), so standard windows appear **behind** fullscreen content.

**Relevant Tauri Issues:**

- [Show window on top of full-screen app #5793](https://github.com/tauri-apps/tauri/issues/5793)
- [visibleOnAllWorkspaces not working with fullscreen #11488](https://github.com/tauri-apps/tauri/issues/11488)

## Solution

Use NSPanel instead of NSWindow. Only `NSPanel` windows can appear above fullscreen apps.

## Implementation

Uses [tauri-nspanel](https://github.com/ahkohd/tauri-nspanel) plugin (v2.1), which seems to be the best option here. [Cap](https://github.com/CapSoftware/Cap) and [Overlayed](https://github.com/overlayeddev/overlayed) both use it in prod, and any other options add significantly more macOS-specific code.

Only `create_recording_overlay()` needs to be platform-conditional. Other overlay functions (`show`, `hide`, `update_position`, etc.) can remain platform-agnostic because `PanelBuilder` creates a standard Tauri window first, **then converts it to NSPanel** — the window remains registered in Tauri's manager, accessible via `get_webview_window()`.

The NSPanel has:

- High window level (`PanelLevel::Status` - level 25)
- `canJoinAllSpaces` - appears in all Mission Control spaces
- `fullScreenAuxiliary` - works alongside fullscreen apps

## Changes

1. `src-tauri/Cargo.toml` - Added tauri-nspanel dependency for macOS builds
2. `src-tauri/src/lib.rs` - Initialize plugin on macOS
3. `src-tauri/src/overlay.rs` - Platform-conditional panel creation

- No frontend changes – React/CSS overlay components untouched.
- `macOSPrivateApi: true` required in `tauri.conf.json` (this was already enabled)

## What I've tested

Build tested on macOS Tahoe 26.0.1 (Apple Silicon):

- [x] Works accross fullscreen apps (closes #277)
- [x] Works when switching spaces while recording overlay is active (closes #278)
- [x] No changes to existing UI or behavior (that I could find at least)

## What I can't test

- [ ] Builds for Win/Linux still work fine
- [ ] Signed builds for macOS actually work (coz urgh Tauri can sometimes be annoying here)

## References

- [tauri-nspanel documentation](https://github.com/ahkohd/tauri-nspanel)
- [macOS Window Levels](https://developer.apple.com/documentation/appkit/nswindowlevel)
- [NSWindow.CollectionBehavior](https://developer.apple.com/documentation/appkit/nswindow/collectionbehavior)
- [Stack Overflow: NSPanel above fullscreen](https://stackoverflow.com/questions/36205834/allow-an-nswindow-nspanel-to-float-above-full-screen-apps)

### CODE REVIEW

**Comment by dannysmith** [comment]
Also...

1. Have included an unrelated commit to gitignore `*.local.*` because it didn't seem worth a separate PR.
2. @cjpais thanks for making this - appreciate the work mate 🙏

File: src-tauri/src/overlay.rs [hunk 1]
```diff
@@ -1,8 +1,29 @@
 use crate::settings;
 use crate::settings::OverlayPosition;
 use enigo::{Enigo, Mouse};
+use tauri::{AppHandle, Emitter, Manager, PhysicalPosition, PhysicalSize};
+
+#[cfg(not(target_os = "macos"))]
```
Comment (cjpais) [inline src-tauri/src/overlay.rs:6]: what was the reason for this? is it just unused on the macOS func?

**Comment by cjpais** [comment]
well works for me, we can make tweaks later. im gonna merge it, thanks!

File: src-tauri/src/overlay.rs (hunk 1 above)
Comment (dannysmith) [reply src-tauri/src/overlay.rs:6]: Yep exactly that
